@startuml
left to right direction
rectangle Biblioteca{
(Reservar Libro)
(Prestar Libro)
(Devolver Libro)
(Actualizar catálogo)
}
:Socio: -- (Reservar Libro)
:Socio: -- (Prestar Libro)
:Socio: -- (Devolver Libro)
:Bibliotecario: -- (Prestar Libro)
:Bibliotecario: -- (Actualizar catálogo)
@enduml